name: ci_workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests: 
    runs-on: ubuntu-latest
  
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Launch application
        run: |
          docker compose up --build -d
          npx wait-port http://localhost:8080/api/health -t 30000

      - name: Run UI tests
        working-directory: ./tests-e2e
        run: |
          npm ci
          npx playwright install
          npx playwright test

      - name: Shutdown application
        run: |
          docker compose down

      - name: UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: ./tests-e2e/test-results/
          retention-days: 7

      - name: UI Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name: ui-test-report
          path: ./tests-e2e/playwright-report/
          retention-days: 7
      
      - name: Publish UI Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with: 
          name: UI Test Results
          path: ./tests-e2e/test-results/*.xml
          reporter: jest-junit
